plugins {
    id 'dev.yumi.gradle.licenser' version '2.2.2' apply false
    id 'com.gradleup.shadow' version '8.3.8' apply false
}

import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent

allprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'idea'
    apply plugin: 'java-library'
    apply plugin: 'dev.yumi.gradle.licenser'

    ext {
        baseVersion = '1.10'
        patchVersion = 0
        pluginVersion = rootProject.mod_version
        pluginDescription = 'spark is a performance profiling plugin/mod for Minecraft clients, servers and proxies.'
        applyExcludes = { Jar jarTask ->
            jarTask.exclude 'module-info.class'
            jarTask.exclude 'META-INF/maven/**'
            jarTask.exclude 'META-INF/proguard/**'
            jarTask.exclude 'META-INF/LICENSE'
            jarTask.exclude 'META-INF/NOTICE'
            jarTask.exclude '**/*.proto'
            jarTask.exclude '**/*.proto.bin'
            jarTask.exclude 'linux-arm64/**'
            jarTask.exclude 'linux-x64/**'
            jarTask.exclude 'macos/**'
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 17
    }

    tasks.withType(Test).configureEach {
        testLogging {
            events = [TestLogEvent.PASSED, TestLogEvent.FAILED, TestLogEvent.SKIPPED]
            exceptionFormat = TestExceptionFormat.FULL
            showExceptions = true
            showCauses = true
            showStackTraces = true
        }
    }

    processResources {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }

    license {
        rule(rootProject.file('HEADER.txt'))
    }

    repositories {
        maven { name = 'Legacy Fabric'; url = 'https://maven.legacyfabric.net' }
        maven { name = 'Babric'; url = 'https://maven.glass-launcher.net/babric' }
        maven { url = 'https://api.modrinth.com/maven' }
        maven { url = 'https://btw-community.github.io/btw-mvn/' }
        mavenCentral()
        maven { url = 'https://repo.lucko.me/' }
    }
}
