pluginManagement {
    repositories {
        maven { url = 'https://BTW-Community.github.io/BTW-gradle' }
        maven { name = 'Fabric'; url = 'https://maven.fabricmc.net/' }
        maven { name = 'Legacy Fabric'; url = 'https://maven.legacyfabric.net' }
        maven { name = 'Jitpack'; url = 'https://jitpack.io' }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'spark-btw'
include 'spark-api', 'spark-common', 'spark-btw'
